authors:
  gabrielbdornas:
    name: Gabriel Braico Dornas
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/49699290
  andrelamor:
    name: André Luiz Guimarães Amorim
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/52294411?v=4
  Isabelle-Fernandes:
    name: Isabelle Fernandes de Oliveira
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/65547646?v=4
